server:
  port: 8020
spring:
  application:
    name: injournal-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tb_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: zhouchongru1
    driver-class-name: com.mysql.jdbc.Driver